In [1]:
import numpy as np

In [3]:
my_list = [0, 1, 2, 3]

In [4]:
my_list

[0, 1, 2, 3]

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3])

In [11]:
np.arange(0, 7, 2)

array([0, 2, 4, 6])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.random.seed(101)

arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
arr.min()

9

In [28]:
arr.max()

95

In [33]:
arr.mean()
arr.reshape(1,10)

array([[95, 11, 81, 70, 63, 87, 75,  9, 77, 40]])